name: Slabutils
version: '${project.version}'
main: fr.supermax_8.slabutils.Slabutils
api-version: 1.16
authors: [ SuperMax_8 ]
description: Now you can break 1/2 of the slabs
commands:
  nightvision:
    description: Night vision
    permission: slabutils.commands
    aliases: nv
  vanish:
    description: Vanish
    permission: slabutils.commands
    aliases: v